import Navbar from "@/components/Header";
import HeroSection from "@/components/hero";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="z-[-1]">
          <HeroSection />
        </div>
        {children}
      </body>
    </html>
  );
}
