"use client";
import BarcodeScanner from "./Barcode";
import { TextResult } from "dynamsoft-javascript-barcode";
import Head from "next/head";
import React from "react";
// import homeStyles from "../styles/Home.module.css";

export default function Home() {
  const [isActive, setIsActive] = React.useState(false);
  const [initialized, setInitialized] = React.useState(false);

  const toggleScanning = () => {
    setIsActive(!isActive);
  };

  const onScanned = (results: TextResult[]) => {
    if (results.length > 0) {
      let text = "";
      for (let index = 0; index < results.length; index++) {
        const result = results[index];
        text =
          text + result.barcodeFormatString + ": " + result.barcodeText + "\n";
      }
      alert(text);
      setIsActive(false);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bgblack">
          <h2>Next.js Barcode Scanner</h2>
          {initialized ? (
            <button onClick={toggleScanning}>
              {isActive ? "Stop Scanning" : "Start Scanning"}
            </button>
          ) : (
            <div>Initializing...</div>
          )}
          <div className="bg-white">
            <BarcodeScanner
              onInitialized={() => setInitialized(true)}
              isActive={isActive}
              onScanned={onScanned}
            />
          </div>
        </div>
      </main>
    </>
  );
}
